```{r msummary, message=FALSE, warning=FALSE}
library(fixest) ## For quick multi-model regression object

mods = feols(c(mpg, hp) ~ disp + csw(wt, drat) | cyl + vs, data = mtcars)

library(modelsummary)
library(kableExtra)

msummary(
  mods, 
  title = "fixest: multi-model estimation", 
  stars = TRUE,
  gof_omit = "Adj|Pseudo|Log|AIC|BIC"
  ) %>%
  add_footnote(
    c(paste("This footnote is pretty long. In fact, it runs over several lines",
          "of standard PDF output. Luckily that's no problem thanks to",
          "modelsummary, kableExtra, and threeparttable. As an aside, the",
          "fixest package is also amazing and you should use it."),
      "A shorter note."),
    threeparttable = TRUE
    ) %>%
  kable_styling(latex_options = "hold_position") ## (Optional) Print table directly below code
```

### PDF support for non-standard fonts

This is an easy one; simply a matter of adding `dev: cairo_pdf` to the YAML. But it's nice not having to remember that every time, no?

*Note: As the figure caption suggests, to run this next chunk you'll need to add [Arial Narrow](https://docs.microsoft.com/en-us/typography/font-list/arial-narrow) to your font book if it's not installed on your system already.*

```{r mpg, message=FALSE}
library(ggplot2)
library(hrbrthemes)

ggplot(mtcars, aes(mpg, wt)) +
  geom_point() +
  labs(x = "Fuel efficiency (mpg)", y = "Weight (tons)",
       title = "This plot uses Arial Narrow fonts",
       caption = "Note: Fonts must be installed separately on your system.") + 
  theme_ipsum()
```