---
title: "19119461 Bootcamp Assignment"
output: github_document
author: "Pablo Rees\n"
date: "26 January 2022"
---

##Task 2: non-displayed
```{r 1_document_setup, include=FALSE}
#include = FALSE prevents the knitted document from displaying this code chunk
knitr::opts_chunk$set(echo = TRUE, eval = TRUE, fig.height = 3.5, fig.width = 6)
library(pacman)
pacman::p_load(tidyverse, huxtable, fixest, urca)
```

##Task 3: Augmented Dickey-Fuller
```{r ADF, echo=FALSE}
ts_df <- read.csv(file = "data/ts_data.csv", header = TRUE)
ts_df <- ts_df %>% mutate(Year = as.Date(Year, format = "%Y-%m-%d")) %>%
  dplyr::filter(Country == "France") %>%
  dplyr::filter(Year >= as.Date("1985-01-01"), Year <= "2010-01-01") %>%
  arrange(Year) 

Consumption_df <- ts_df %>% dplyr::select(ln_consump_pc)

test_vector <- Consumption_df%>% pull(ln_consump_pc)

my_ADF1 <- ur.df(
  y= test_vector, #vector
  type = "trend",
  lags = 5,
  selectlags = "AIC")

summary(my_ADF1)
 
```


##Task 4: Regressions
```{r Regression, echo=FALSE}
cs_df <- read_csv(file = "data/cs_data.csv")
model1 <- feols(wage ~ x1, data = cs_df) 
model2 <- feols(wage ~ x1 + x2, data = cs_df) 
model3 <- feols(wage ~ x1 + x2 + i(treat), data = cs_df) # i(treat) considers treat as a categorical variable

huxreg("Model 1" = model1, "Model 2" = model2, "Model 3" = model3, # choose statistics to display
       statistics = c("N" = "nobs", "R-squared" = "r.squared"),
       # change stars criteria
       stars = c(`*` = 0.1, `**` = 0.05, `***` = 0.01, `****` = 0.001), # rounded to 2 decimals
       number_format = 2
) %>%
  # The following are huxtable commands and are also piped
  set_font_size(8) %>%
  set_align(10:11, 2:4, value = "center") %>%
  set_caption("Cross section regressions")


```



