---
title: "22211187"
output: github_document
---

##Task 2 
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = TRUE, fig.height = 3.5, fig.width = 6,warning=F)
```

```{r task_2}
library(pacman)
pacman::p_load(tidyverse, huxtable, fixest, urca)
```

##Task 3

```{r task_3}
ts_data <- read.csv(file = "data/ts_data.csv", header = TRUE)
ts_data <- ts_data %>% mutate(Year=as.Date(Year, format="%Y-%m-%d"))
tsdata_filtered <- ts_data %>% dplyr::filter(Country=="France", Year >= as.Date("1985-01-01"), Year <= as.Date("2010-01-01"))
tsdata_filtered <- tsdata_filtered %>% arrange(Year)
test_vector <- tsdata_filtered %>% pull(ln_consump_pc)
ADF1 <- ur.df(y=test_vector,type="trend",lags=5,selectlags="AIC")
summary(ADF1)

```
##Task 4
```{r task_4}
cs_data <- read.csv(file="data/cs_data.csv", header= TRUE)
model1 <- feols(wage ~ x1,data=cs_data)
model2 <- feols(wage~x1+x2,data=cs_data)
model3 <- feols(wage~x1+x2+i(treat),data=cs_data)
huxreg(model1,model2,model3,statistics=c("N"="nobs","R-squared"="r.squared"),number_format=2) %>% set_align(9:10, 2:4,value="center") %>% set_caption("Regression Output")

```

